import type { FastifyInstance } from "fastify";
import { authRoutes } from "./auth.routes.js";
import { catalogRoutes } from "./catalog.routes.js";
import { progressRoutes } from "./progress.routes.js";
import { newsRoutes } from "./news.routes.js";
import { homeworkRoutes } from "./homework.routes.js";
import { homeworkReviewRoutes } from "./homework-review.routes.js";
import { learningRoutes } from "./learning.routes.js";
import { cmsRoutes } from "./cms.routes.js";
import { mediaRoutes } from "./media.routes.js";
import { pushRoutes } from "./push.routes.js";
import { lessonQuestionsRoutes } from "./lesson-questions.routes.js";
import { onlineLessonsRoutes } from "./online-lessons.routes.js";
import { notificationsRoutes } from "./notifications.routes.js";
import { studentsAdminRoutes } from "./students-admin.routes.js";
import { usersAdminRoutes } from "./users-admin.routes.js";
import { schoolOfflineRoutes } from "./school-offline.routes.js";
import { teacherOfflineRoutes } from "./teacher-offline.routes.js";
import { adminOfflineRoutes } from "./admin-offline.routes.js";
import { publicTrialRoutes } from "./public-trial.routes.js";
import { messagesRoutes } from "./messages.routes.js";
import { adminOverviewRoutes } from "./admin-overview.routes.js";
import { preparedTestsRoutes } from "./prepared-tests.routes.js";
import { rewardsRoutes } from "./rewards.routes.js";
import { weeklyLeagueRoutes } from "./weekly-league.routes.js";
import { familyRoutes } from "./family.routes.js";
import { studentTasksRoutes } from "./student-tasks.routes.js";
import { learningHomeworkRoutes } from "./learning-homework.routes.js";
import { adminJournalRoutes } from "./admin-journal.routes.js";
import { learningDialogRoutes } from "./learning-dialog.routes.js";
import { improvementSuggestionRoutes } from "./improvement-suggestions.routes.js";
import { appUsageRoutes } from "./app-usage.routes.js";
import { appAnalyticsRoutes } from "./app-analytics.routes.js";
import { homeworkStatisticsRoutes } from "./homework-statistics.routes.js";
import { shopRoutes } from "./shop.routes.js";

export async function registerRoutes(app: FastifyInstance) {
  await app.register(async (api) => {
    await api.register(authRoutes);
    await api.register(catalogRoutes);
    await api.register(progressRoutes);
    await api.register(learningRoutes);
    await api.register(newsRoutes);
    await api.register(homeworkRoutes);
    await api.register(homeworkReviewRoutes);
    await api.register(cmsRoutes);
    await api.register(mediaRoutes);
    await api.register(pushRoutes);
    await api.register(lessonQuestionsRoutes);
    await api.register(onlineLessonsRoutes);
    await api.register(notificationsRoutes);
    await api.register(messagesRoutes);
    await api.register(studentsAdminRoutes);
    await api.register(usersAdminRoutes);
    await api.register(schoolOfflineRoutes);
    await api.register(teacherOfflineRoutes);
    await api.register(adminOfflineRoutes);
    await api.register(adminOverviewRoutes);
    await api.register(preparedTestsRoutes);
    await api.register(rewardsRoutes);
    await api.register(weeklyLeagueRoutes);
    await api.register(familyRoutes);
    await api.register(studentTasksRoutes);
    await api.register(learningHomeworkRoutes);
    await api.register(adminJournalRoutes);
    await api.register(learningDialogRoutes);
    await api.register(improvementSuggestionRoutes);
    await api.register(appUsageRoutes);
    await api.register(appAnalyticsRoutes);
    await api.register(homeworkStatisticsRoutes);
    await api.register(shopRoutes);
    await api.register(publicTrialRoutes);
  }, { prefix: "/api/v1" });
}
